#配置项目名，解压WAR包后文件夹的名称，没有这个就是默认项目名称和路径 "/"
server:
  servlet:
    context-path: /sqltest
  port: 8081

# mybatis #
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/**/*.xml

#spring
spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource  # 配置当前要使用的Druid数据库连接池
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #jdbc-url: jdbc:sqlserver://120.24.179.236:1433;DatabaseName=nanhuadata
    #username: sa
    #password: 8information8

    one:
      druid:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://120.24.179.236:1433;DatabaseName=test
        username: sa
        password: 8information8

  ###################以下为druid增加的配置###########################

      # 连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置

        #使用Druid数据源
        initial-size: 3
        max-active: 20
        min-idle: 3
        max-wait: 60000
        validation-query: select 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 3000

        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙， spring.datasource.druid.filters=slf4j
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    two:
      druid:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://120.24.179.236:1433;DatabaseName=test
        username: sa
        password: 8information8

  ###################以下为druid增加的配置###########################

      # 连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置

        #使用Druid数据源
        initial-size: 3
        max-active: 20
        min-idle: 3
        max-wait: 60000
        validation-query: select 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 3000

        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙， spring.datasource.druid.filters=slf4j
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000




  messages: #资源信息
    basename: i18n/Messages,i18n/Pages

